name: flutter_study_guide
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  dio: ^5.1.1
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  talker_flutter: ^4.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
     - assets/fonts/
